site_name: GPTChangelog
site_description: Automatically generate detailed changelogs from git commit history using AI
site_url: https://xjodoin.github.io/gptchangelog/
repo_url: https://github.com/xjodoin/gptchangelog
repo_name: xjodoin/gptchangelog
site_author: xjodoin
edit_uri: edit/main/docs/
copyright: Copyright (c) 2025 Xavier Jodoin
strict: true

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.svg
  favicon: assets/images/logo.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

plugins:
  - search:
      lang: en
  - sitemap
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Configuration: user-guide/configuration.md
    - Basic Usage: user-guide/basic-usage.md
    - Advanced Usage: user-guide/advanced-usage.md
    - Templates: user-guide/templates.md
  - Developer Guide:
    - Contributing: developer-guide/contributing.md
    - Architecture: developer-guide/architecture.md
    - API Reference: developer-guide/api-reference.md
  - Examples: examples.md
  - Changelog: changelog.md

extra:
  version: 0.9.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xjodoin/gptchangelog
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/gptchangelog/
  social_image: assets/images/logo.png
